# Generated by Django 3.0 on 2020-02-25 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allrecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('chef', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_state', models.CharField(max_length=500)),
                ('food_taste', models.CharField(max_length=500)),
                ('food_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_recipes.Allrecipes')),
            ],
        ),
    ]
